config/routes.rb
Rails.application.routes.draw do
  
  resources :tenants do
    resources :projects
  end
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "milia/registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }


end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :tenant
  validates_uniqueness_of :title
  validate :free_plan_can_only_have_one_project
  
  def free_plan_can_only_have_one_project
    if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == free)
      errors.add(:base, "Free plans cannot have more than one project")
    end
  end
  
  def self.by_plan_and_tenant(tenant_id)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      tenant.projects
    else
      tenant.projects.order(:id).limit(1)
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_tenant, only: [:show, :edit, :update, :detroy, :new, :create]
  before_action :verify_tenant

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_url, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_completion_date, :tenant_id)
    end
    
    def set_tenant
      @tenant = Tenant.find(params[:tenant.id])
    end
    
    def verify_tenant
      unless params[:tenant.id] == Tenant.current_tenant_id.to_s
        redirect_to :root, flash: {error: 'You are not authorized to access any organization other than your own'}
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@tenant,@project] do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="control-group">
    <%= f.label :expected_completion_date, :class => 'control-label' %><br>
    <div class="controls">
      <%= f.text_field :expected_completion_date, :class => 'form-control datepicker' %>
    </div>
  </div>
  <div class="actions">
    <br />
    <%= f.hidden_field :tenant_id, value: params[:tenant_id], :class => 'form-control' %>
    <%= f.submit %>
    <%= link_to t('.cancel', :default => t("Helper.links.cancel")), root_path, :class => 'btn btn-default' %>
    
  </div>
<% end %>

app/views/projects/_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>
<% if @projects.size > 0 %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Expected completion date</th>
      <th>Tenant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title,
                tenant_project_path(project,tenant_id:@tenant.id), class: 'main-link' %></td>
        <td><%= project.details %></td>
        <td><%= project.expected_completion_date %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_tenant_project_path(project,tenant_id: @tenant.id), :class => 'btn btn default btn-xs' %></td>
        <td><%= link_to 'Destroy', tenant_project_path(project, tenant_id: @tenant.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
<p class="lead">
  You don't have any projects
</p>
<% end %>

<% if (@tenant.can_create_project?) %>
  <%= link_to 'New Project', new_tenant_project_path(tenant_id: @tenant.id) %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h3><%= @project.title %></h3>
  <h3><small>Organization - <%= tenant_name @project.tenant_id %><small></h3>
</div>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>

<p>
  <strong>Expected completion date:</strong>
  <%= @project.expected_completion_date %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @project.tenant %>
</p>

<%= link_to 'Back to Organization Home', root_path %>
<%= link_to 'Edit', edit_tenant_project_path(project: @project, tenant: @project.tenant_id) %> 
<%= link_to 'Destroy', tenant_project_path(project: @project, tenant: @project.tenant_id), :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
            :class => 'btn btn-danger'%> 